### ISSUE TITLE
Invalid parameters are forwarded to `plot()` in `plot.R0.R()`

### ISSUE THREAD

**Issue by Bisaloo** [tobadia/R0#11]
`plot.R0.R()` forwards a `xscale` and a `TD.split` arguments to internal plotting functions. But these arguments only exist for `plotRTD()`, and not for, e.g., `plotRML()`. 
So when these arguments are passed to any function other than `plotRTD()`, they will end up in the `...` which is forwarded to `graphics::plot.default()`. This results in warnings about invalid graphical parameters.

Reproducible example:

``` r
library(R0)
#> Loading required package: MASS

data(Germany.1918)

mGT <- generation.time("gamma", c(2.45, 1.38))

res <- est.R0.ML(Germany.1918, mGT, begin = 1, end = 27, range = c(0.01, 50))

plot(res)
#> Warning in plot.window(...): "xscale" is not a graphical parameter
#> Warning in plot.window(...): "TD.split" is not a graphical parameter
#> Warning in plot.xy(xy, type, ...): "xscale" is not a graphical parameter
#> Warning in plot.xy(xy, type, ...): "TD.split" is not a graphical parameter
#> Warning in axis(side = side, at = at, labels = labels, ...): "xscale" is not a
#> graphical parameter
#> Warning in axis(side = side, at = at, labels = labels, ...): "TD.split" is not a
#> graphical parameter
#> Warning in axis(side = side, at = at, labels = labels, ...): "xscale" is not a
#> graphical parameter
#> Warning in axis(side = side, at = at, labels = labels, ...): "TD.split" is not a
#> graphical parameter
#> Warning in box(...): "xscale" is not a graphical parameter
#> Warning in box(...): "TD.split" is not a graphical parameter
#> Warning in title(...): "xscale" is not a graphical parameter
#> Warning in title(...): "TD.split" is not a graphical parameter
```

![](https://i.imgur.com/tWGR2dC.png)

<sup>Created on 2022-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by tobadia** [comment]
Vastly overdue... But I've finally started revamping the package. The first step was moving to Roxygen2 for all docs, which I have just merged into master today.

I'll be including a fix for this in a commit momentarily. The next step will be to revamp the actual _code_, which is... ugly. 10-year-ago me could really need some cleanup lessons. This will take more time, and the fix I'm going to push will probably be obsolete after revamping the code, but for now, it'll do !
